# Generated by Django 4.2.8 on 2023-12-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksbardari',
            fields=[
                ('nobatid', models.IntegerField(db_column='nobatID', primary_key=True, serialize=False)),
                ('akstype', models.CharField(db_column='aksType', max_length=11)),
            ],
            options={
                'db_table': 'Aksbardari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bazneshastegi',
            fields=[
                ('bazneshateid', models.BigIntegerField(db_column='bazneshateID', primary_key=True, serialize=False)),
                ('bazneshastestatus', models.CharField(db_column='bazneshasteStatus', max_length=3)),
                ('daramad', models.DecimalField(blank=True, db_column='Daramad', decimal_places=4, max_digits=19, null=True)),
                ('zamanbazneshastegi', models.CharField(db_column='zamanBazneshastegi', max_length=4)),
            ],
            options={
                'db_table': 'Bazneshastegi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bimari',
            fields=[
                ('nobatidpaziresh', models.IntegerField(db_column='nobatIDPaziresh', primary_key=True, serialize=False)),
                ('bimaritype', models.CharField(db_column='bimariType', max_length=500)),
            ],
            options={
                'db_table': 'Bimari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bimarorganci',
            fields=[
                ('codemeli', models.BigIntegerField(db_column='codeMeli', primary_key=True, serialize=False)),
                ('bimaristatus', models.TextField(blank=True, db_column='bimariStatus', null=True)),
            ],
            options={
                'db_table': 'BimarOrganci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('lastname', models.CharField(db_column='lastName', max_length=300, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=300)),
                ('takhasos', models.CharField(max_length=200)),
                ('sabege', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Erja',
            fields=[
                ('raeischeked', models.IntegerField(db_column='raeisCheked')),
                ('erjaaddress', models.TextField(blank=True, db_column='erjaAddress', null=True)),
                ('erjatype', models.CharField(blank=True, db_column='erjaType', max_length=8, null=True)),
                ('erjastatus', models.CharField(db_column='erjaStatus', max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Erja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herasat',
            fields=[
                ('residegiid', models.IntegerField(db_column='residegiID', primary_key=True, serialize=False)),
                ('shekayatstatus', models.CharField(db_column='shekayatStatus', max_length=500)),
            ],
            options={
                'db_table': 'Herasat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Karmand',
            fields=[
                ('karmandid', models.IntegerField(db_column='karmandID', primary_key=True, serialize=False)),
                ('mahalkar', models.CharField(db_column='mahalKar', max_length=50)),
                ('sabege', models.SmallIntegerField()),
                ('daramad', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('bazneshaste', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Karmand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Omormalyati',
            fields=[
                ('karmandmalyatid', models.BigIntegerField(db_column='karmandMalyatID', primary_key=True, serialize=False)),
                ('kasrimalyati', models.DecimalField(db_column='kasriMalyati', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'OmorMalyati',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organc',
            fields=[
                ('organcpazireshid', models.IntegerField(db_column='organcPazireshID', primary_key=True, serialize=False)),
                ('organcitype', models.TextField(blank=True, db_column='organciType', null=True)),
            ],
            options={
                'db_table': 'Organc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paziresh',
            fields=[
                ('codemeli', models.BigIntegerField(db_column='codeMeli', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Paziresh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('nobatid', models.IntegerField(db_column='nobatID', primary_key=True, serialize=False)),
                ('darooname', models.CharField(db_column='darooName', max_length=300)),
                ('daroonumber', models.CharField(blank=True, db_column='darooNumber', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raeis',
            fields=[
                ('codenezampezeshki', models.BigIntegerField(db_column='codeNezamPezeshki', primary_key=True, serialize=False)),
                ('vipid', models.IntegerField(db_column='VIPID')),
                ('sabegeryasat', models.SmallIntegerField(db_column='sabegeRyasat')),
            ],
            options={
                'db_table': 'Raeis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shekayat',
            fields=[
                ('codemelishaki', models.BigIntegerField(db_column='codeMeliShaki', primary_key=True, serialize=False)),
                ('shekayattype', models.CharField(db_column='shekayatType', max_length=500)),
                ('addressshaki', models.TextField(blank=True, db_column='addressShaki', null=True)),
            ],
            options={
                'db_table': 'Shekayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Morajegar',
            fields=[
                ('codemeli', models.OneToOneField(db_column='codeMeli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='darmangah.paziresh')),
                ('age', models.SmallIntegerField()),
                ('firstname', models.CharField(db_column='firstName', max_length=100)),
                ('lastname', models.CharField(db_column='lastName', max_length=300)),
            ],
            options={
                'db_table': 'Morajegar',
                'managed': False,
            },
        ),
    ]
